services:
  - type: web
    name: xpvault-backend
    dockerfilePath: ./Dockerfile
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/xpvault-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: xpvault-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: xpvault-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: xpvault-db
          property: password
